name: CSCLEDE-X86-64
on: 
  #push:
  #  branches: 
  #    - master
  release:
    types: [published]
  #schedule:
  #  - cron: 15 20 14 * *
  watch:
    types: [started]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        docker rmi `docker images -q`
        echo "Deleting files, please wait ..."
        sudo rm -rf \
          /usr/share/dotnet \
          /etc/mysql \
          /etc/php
        sudo -E apt-get -y purge \
          azure-cli \
          ghc* \
          zulu* \
          hhvm \
          llvm* \
          firefox \
          google* \
          dotnet* \
          powershell \
          openjdk* \
          mysql* \
          php*
        sudo -E apt-get update
        sudo -E apt-get -y install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev patch unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex node-uglify gcc-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx-ucl libelf-dev autoconf automake libtool autopoint device-tree-compiler libuv-dev libp11-kit-dev
        sudo -E apt-get -y autoremove --purge
        sudo -E apt-get clean
    - name: Clone source code
      env: 
        REPO_URL: https://github.com/coolsnowwolf/lede
        REPO_BRANCH: master
      run: git clone --depth 1 $REPO_URL -b $REPO_BRANCH openwrt
    - name: Clone custom source code
      run: |
        cd openwrt/package
        mkdir coolsong
        cd coolsong
        git clone https://github.com/tzxiaozhen88/luci-app-koolproxyR.git
        git clone https://github.com/rufengsuixing/luci-app-adguardhome.git
        git clone https://github.com/happyzhang1995/openwrt-adguardhome.git
        #git clone https://github.com/Leo-Jo-My/luci-app-ssr-plus-Jo.git
        #git clone https://github.com/Leo-Jo-My/my.git
        #mv my/chinadns my/dnscrypt-proxy-full my/GoQuiet my/openwrt-simple-obfs -t ./
        git clone https://github.com/vernesong/OpenClash.git
        mv OpenClash/luci-app-openclash ./luci-app-openclash
        git clone https://github.com/tty228/luci-app-serverchan.git
        git clone https://github.com/wubin2/luci-theme-argon-my.git
        rm -rf OpenClash && rm -rf my
        #cd luci-theme-argon/htdocs/luci-static/argon
        #wget -O cascade.css https://raw.githubusercontent.com/wubin2/AutoBuild-CSCLEDE/master/cascade.css
    - name: Update & Install feeds
      working-directory: ./openwrt
      run: |
        sed -i 's/192.168.1.1/192.168.1.2/g' package/base-files/files/bin/config_generate
        sed -i '4a src-git lienol https://github.com/Lienol/openwrt-package' feeds.conf.default
        ./scripts/feeds update -a
        rm -rf feeds/lienol/others/luci-app-verysync && rm -rf feeds/lienol/package/shadowsocksr-libev && rm -rf feeds/lienol/package/trojan && rm -rf feeds/lienol/package/v2ray && rm -rf feeds/lienol/package/pdnsd-alt && rm -rf feeds/lienol/package/openssl1.1 && rm -rf feeds/lienol/package/ipt2socks && rm -rf feeds/lienol/package/verysync && rm -rf package/lean/kcptun && rm -rf package/lean/luci-app-kodexplorer && rm -rf package/lean/luci-app-pppoe-relay && rm -rf package/lean/luci-app-pptp-server && rm -rf package/lean/luci-app-v2ray-server && rm -rf package/lean/luci-theme-argon
        ./scripts/feeds install -a
        ./scripts/feeds install -a
        sed -i 's/luci-theme-bootstrap/luci-theme-argon-my/g' feeds/luci/collections/luci/Makefile
    - name: Configuration Customization - Build_x86_64
      env:
        CONFIG_FILE: 'diffconfig_x86_64.config'
      run: |
        [ -e $CONFIG_FILE ] && mv $CONFIG_FILE openwrt/.config
        chmod +x ./customize.sh && ./customize.sh
        cd openwrt && make defconfig
    #- name: SSH connection to Actions
    #  uses: wubin2/AutoBuild-CSCLEDE@master
    - name: Download package
      working-directory: ./openwrt
      run: |
        make download -j$(nproc)
        find dl -size -1024c -exec ls -l {} \;
        find dl -size -1024c -exec rm -f {} \;
    - name: Build firmware
      working-directory: ./openwrt
      run: |
        echo -e "$(nproc) thread build."
        make -j$(nproc) V=s
    - name : Upload artifact
      uses: actions/upload-artifact@master
      with:
        name: CSCLEDE-X86-64
        path: openwrt/bin
